"""Wasilah YouTube Shorts auto-publisher.

Reuses reels.json / reel_captions.json (same queue as IG + FB) and uploads each
due reel to the Wasilah channel as a Short. Self-healing: state lives in
posted_youtube.json, so a failed or skipped reel is simply retried next run.

Secrets: YT_CLIENT_ID, YT_CLIENT_SECRET, YT_REFRESH_TOKEN.

Quota note: a video insert costs 1600 units against a 10,000/day default, so at
most 6 uploads a day are possible. MAX_PER_RUN caps below that and any deferred
reels are logged explicitly, never dropped silently.
"""
import datetime, json, os, re, ssl, urllib.error, urllib.parse, urllib.request

TOKEN_URL = "https://oauth2.googleapis.com/token"
UPLOAD_URL = ("https://www.googleapis.com/upload/youtube/v3/videos"
              "?uploadType=resumable&part=snippet,status")
CFG = json.load(open("config.json"))
CAPS = json.load(open("reel_captions.json"))
# Per-reel YouTube metadata: a Bangla query phrase in front of the existing
# English line, plus a deep link to the article on that topic. Generated by
# build_youtube_meta.py, which is where the copy lives. Optional on purpose: if
# the file is missing or a reel is not in it, the caption-derived fallback below
# still produces a valid upload rather than failing the run.
META = json.load(open("youtube_meta.json", encoding="utf-8")) \
    if os.path.exists("youtube_meta.json") else {}
# Shorts wants 9:16. `videoBase` holds the 1080x1350 feed masters that Instagram
# and Facebook publish, and pointing YouTube at those put the first 7 uploads on
# the channel at 4:5, letterboxed instead of full screen. Verified against the
# Data API on 2026-08-02, not inferred. So YouTube reads its own base and the
# feed publishers are left alone. Falls back to the 4:5 base only if the 9:16
# one is absent, which is a visible-but-working degrade rather than a crash.
VIDEO_BASE = CFG.get("videoBase916") or CFG["videoBase"]
# One a day, matching TikTok. Six was a drain rate for the back catalogue and the
# quota ceiling allows it, but a channel posting six while the other posts one is
# not the same post on every platform. See build_daily.py.
MAX_PER_RUN = int(os.environ.get("YT_MAX_PER_RUN", "1"))
CATEGORY_ID = "22"          # People & Blogs
SKIPPED = "skipped_youtube.json"
PRIVACY = os.environ.get("YT_PRIVACY", "public")
# Content ID gate. The four-ayah d-series carries Mishary Alafasy recitation, and
# several of those recordings are registered to commercial claimants whose policy
# is block-globally. YouTube's own wording on the two that went down: "Your Short
# can't be played because it contains claimed content that exceeds the length
# limits set by the copyright holder." Verified in Studio on 2026-08-26: d03
# (1:09) and d04 (1:35) blocked globally, while d01 (0:57) and d02 (0:59) carry
# the same Alafasy claims marked "no impact on the video's reach". Duration is
# the only observable separating them, so anything longer is held back rather
# than spent on an upload nobody can play. A held asset is NOT written to
# posted_youtube.json, so it publishes normally once re-rendered with a reciter
# that is not Content ID registered. The claims are not strikes and the channel
# is not at risk either way.
# An asset missing from durations.json is allowed through on purpose: an unknown
# length degrades to the previous behaviour instead of silently muting the queue.
# Armed at 60 on 2026-08-26 while the queue still held Alafasy audio. Disarmed
# the same night once every remaining asset (d05 to d45) was re-rendered with
# Ad-Dussary, whose claims are track-only, which makes length irrelevant. 0 is
# off. Re-arm instantly with YT_MAX_SECONDS=60 if a Short ever comes back
# blocked; durations.json is kept current for exactly that reason.
MAX_SECONDS = float(os.environ.get("YT_MAX_SECONDS", "0"))
DURATIONS = json.load(open("durations.json", encoding="utf-8")) \
    if os.path.exists("durations.json") else {}
HELD = "held_youtube.json"


def access_token():
    data = urllib.parse.urlencode({
        "client_id": os.environ["YT_CLIENT_ID"],
        "client_secret": os.environ["YT_CLIENT_SECRET"],
        "refresh_token": os.environ["YT_REFRESH_TOKEN"],
        "grant_type": "refresh_token",
    }).encode()
    req = urllib.request.Request(TOKEN_URL, data=data, method="POST")
    return json.loads(urllib.request.urlopen(req, timeout=30).read())["access_token"]


def asset_id(rid):
    # matches run_reels.asset_id: a cycle suffix reuses the same file
    m = re.fullmatch(r"(.+?)c\d+", rid)
    return m.group(1) if m else rid


def video_url(reel):
    return f"{VIDEO_BASE}/{asset_id(reel)}.mp4"


def over_limit(reel):
    """Length in seconds if this asset is too long to publish, else None."""
    if not MAX_SECONDS:
        return None
    d = DURATIONS.get(asset_id(reel))
    return d if d is not None and d > MAX_SECONDS else None


def title_for(cap):
    """Fallback title: first English sentence, trimmed, marked as a Short.

    Only used for a reel absent from youtube_meta.json. On its own this produces
    titles like "Slow down #Shorts", which match no search anyone performs, so
    the meta file is the intended path and this is the safety net.
    """
    first = cap.strip().split("\n")[0]
    sentence = re.split(r"(?<=[.!?…])\s", first)[0]
    t = sentence.strip().strip(".… ").replace("<", "").replace(">", "")
    if len(t) > 80:
        t = t[:77].rsplit(" ", 1)[0] + "..."
    return f"{t} #Shorts"


def tags_for(cap):
    """Fallback tags: the caption's own hashtags.

    The 45 verse captions carry none at all, which is how those uploads went out
    untagged. youtube_meta.json supplies a real set for every reel.
    """
    return re.findall(r"#(\w+)", cap)[:15]


def snippet_for(reel, cap):
    """Metadata for one upload, preferring youtube_meta.json over the fallback."""
    m = META.get(reel) or META.get(asset_id(reel))
    if m:
        return m["title"], m["description"], m["tags"]
    return title_for(cap), cap, tags_for(cap)


def fetch_video(reel):
    url = video_url(reel)
    with urllib.request.urlopen(url, timeout=180) as r:
        if r.status != 200:
            raise RuntimeError(f"asset fetch {r.status} for {url}")
        return r.read()


def upload(token, reel, blob):
    cap = CAPS[reel]
    title, description, tags = snippet_for(reel, cap)
    meta = {
        "snippet": {
            "title": title,
            "description": description,
            "tags": tags,
            "categoryId": CATEGORY_ID,
            # The first 13 uploads went out as defaultLanguage bn with
            # defaultAudioLanguage en, which claims a Bangla title over English
            # audio and muddies the language signal both ways. The titles are
            # Bangla-led and the videos carry no speech, so both are bn.
            "defaultLanguage": "bn",
            "defaultAudioLanguage": "bn",
        },
        "status": {
            "privacyStatus": PRIVACY,
            "selfDeclaredMadeForKids": False,
        },
    }
    # Step 1: open a resumable session.
    req = urllib.request.Request(
        UPLOAD_URL, data=json.dumps(meta).encode(), method="POST",
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json; charset=UTF-8",
            "X-Upload-Content-Length": str(len(blob)),
            "X-Upload-Content-Type": "video/mp4",
        })
    try:
        with urllib.request.urlopen(req, timeout=60) as r:
            session = r.headers.get("Location")
    except urllib.error.HTTPError as e:
        return False, f"session error {e.code}: {e.read()[:200].decode(errors='replace')}"
    if not session:
        return False, "no resumable session URL returned"

    # Step 2: send the bytes in one PUT (reels are single-digit MB).
    put = urllib.request.Request(
        session, data=blob, method="PUT",
        headers={"Content-Type": "video/mp4", "Content-Length": str(len(blob))})
    try:
        with urllib.request.urlopen(put, timeout=600) as r:
            res = json.loads(r.read())
    except urllib.error.HTTPError as e:
        return False, f"upload error {e.code}: {e.read()[:200].decode(errors='replace')}"
    vid = res.get("id")
    if not vid:
        return False, f"no video id in response: {str(res)[:200]}"
    return True, vid


def main():
    stamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    # daily.json is the shared queue that TikTok publishes from too, so both
    # channels take the same asset on the same day. It carries `slug` where
    # reels.json carries `reel`; the rest of this function is unchanged, and
    # reels.json remains the fallback so a missing queue degrades to the old
    # behaviour rather than failing the run. IG and FB still read reels.json.
    if os.path.exists("daily.json"):
        reels = [{"reel": e["slug"], "iso": e["iso"]}
                 for e in json.load(open("daily.json", encoding="utf-8"))]
    else:
        reels = json.load(open("reels.json"))
    state = json.load(open("posted_youtube.json")) if os.path.exists("posted_youtube.json") else {}
    now = datetime.datetime.now(datetime.timezone.utc)

    # Ledger is keyed by ASSET, not by queue entry. reels.json recycles a file to
    # a later date (v01-pausesc2 is the same mp4 as v01-pauses); IG and FB happily
    # repost it, but a duplicate upload on YouTube competes with the original and
    # reads as spam. So each distinct video goes up exactly once, ever.
    # DRAIN=1 ignores the reels.json date gate and works through the whole back
    # catalogue at MAX_PER_RUN a day. Set DRAIN=0 once caught up, and YouTube goes
    # back to posting the same evening as IG and FB.
    # DRAIN is now OFF by default. It existed to burn through a back catalogue at
    # six a day, which is precisely what put YouTube 34 assets ahead of TikTok.
    # With the shared queue the schedule IS the plan, so honour it.
    drain = os.environ.get("YT_DRAIN", "0") == "1"
    held = json.load(open(HELD, encoding="utf-8")) if os.path.exists(HELD) else {}
    held_before = dict(held)
    due, seen = [], set()
    for r in reels:
        if not drain and datetime.datetime.fromisoformat(r["iso"].replace("Z", "+00:00")) > now:
            continue
        aid = asset_id(r["reel"])
        if aid in state or aid in seen:
            continue
        seen.add(aid)
        over = over_limit(r["reel"])
        if over is not None:
            held[aid] = {"iso": r["iso"], "seconds": over}
            continue
        due.append(r)
    if held != held_before:
        json.dump(held, open(HELD, "w", encoding="utf-8"),
                  indent=2, ensure_ascii=False, sort_keys=True)
        fresh = sorted(k for k in held if k not in held_before)
        print(f"[{stamp}] held over {MAX_SECONDS:g}s, Content ID would block the "
              f"Short: {', '.join(fresh)} (recorded in {HELD}, not marked posted)")
    if not due:
        print(f"[{stamp}] no YouTube uploads due")
        return

    # Same rule as run_tiktok.py: on a schedule, the newest due entry is the day's
    # post and anything older is recorded, not published late. Two channels each
    # draining their own backlog oldest-first end up posting different videos on
    # the same day, which is the drift daily.json exists to remove. Under DRAIN
    # this does not apply, because there the whole catalogue is deliberately due.
    if not drain and len(due) > 1:
        stale, due = due[:-1], due[-1:]
        missed = json.load(open(SKIPPED, encoding="utf-8")) \
            if os.path.exists(SKIPPED) else {}
        for r in stale:
            missed[asset_id(r["reel"])] = r["iso"]
        json.dump(missed, open(SKIPPED, "w", encoding="utf-8"),
                  indent=2, ensure_ascii=False)
        print(f"[{stamp}] skipped as older than today: "
              f"{[r['reel'] for r in stale]} (recorded in {SKIPPED})")

    batch, deferred = due[:MAX_PER_RUN], due[MAX_PER_RUN:]
    print(f"[{stamp}] mode={'DRAIN (ignoring schedule)' if drain else 'scheduled'}, "
          f"{len(due)} distinct assets outstanding")
    if deferred:
        print(f"[{stamp}] quota cap: uploading {len(batch)}, deferring "
              f"{len(deferred)} to later runs ({', '.join(r['reel'] for r in deferred[:8])}"
              f"{'...' if len(deferred) > 8 else ''})")

    token = access_token()
    for r in batch:
        reel = r["reel"]
        if reel not in CAPS:
            print(f"[{stamp}] YT {reel}: no caption, skipped")
            continue
        try:
            blob = fetch_video(reel)
        except Exception as e:
            print(f"[{stamp}] YT {reel}: asset fetch failed, {e}")
            continue
        ok, info = upload(token, reel, blob)
        if ok:
            state[asset_id(reel)] = info
            print(f"[{stamp}] YT {reel}: published https://youtu.be/{info}")
        else:
            print(f"[{stamp}] YT {reel}: {info}")

    json.dump(state, open("posted_youtube.json", "w"), ensure_ascii=False, indent=2)


if __name__ == "__main__":
    main()
